### ISSUE TITLE
RegisterSubscriber定义的handler无法触发

### ISSUE THREAD

**Issue by yeaze** [micro-in-cn/tutorials#140]
先上主要代码：

```
type Khlog struct{}

func (e *Khlog) Handle(ctx context.Context, msg *khlog.Message) error {
	fmt.Println("I am testing")
	return nil
}

func main() {
	// 使用consul注册
	micReg := consul.NewRegistry(registryOptions)
	service := grpc.NewService(
		micro.Name("kh.micro.srv.khlog"),
		micro.Version("latest"),
		// micro.Address(":2223"),
		micro.Registry(micReg),
		micro.Broker(kafka.NewBroker(brokerOptions)),
	)

	// Initialise service
	service.Init()

	// Register Handler
	khlog.RegisterKhlogHandler(service.Server(), new(handler.Khlog))

	// Register Struct as Subscriber
	micro.RegisterSubscriber("kh.micro.test", service.Server(), new(Khlog))

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

使用了kafka作为消息队列，当我成功发布一个消息到topic：kh.micro.test  之后，我在kafka能看到消息发布成功，但是micro.RegisterSubscriber中定义的handler并没有被执行，没有看到控制台输出：I am testing  字样，说明handler并没有被执行。
查了半天了，不知道问题出在哪里

**Comment by yeaze** [comment]
另外服务起来的时候也能看到订阅topic应该是成功的：

> 2019/09/25 20:38:43 Server [grpc] Listening on [::]:34221
2019/09/25 20:38:43 Broker [kafka] Connected to 127.0.0.1:9092
2019/09/25 20:38:43 Registering node: kh.micro.srv.khlog-e5184367-bcf3-41d3-88f3-107547f2d8a1

**Comment by yeaze** [comment]
这个是消息发布的代码
```
        b := kafka.NewBroker(brokerOptions)
	b.Init()
	err := b.Connect()
	if err != nil {
		fmt.Println("broker connect failed")
		return err
	}

	message := &broker.Message{
		Header: map[string]string{"action": "apply"},
		Body: []byte("提交申请"),
	}

	err = b.Publish("kh.micro.test", message)
	if err != nil {
		fmt.Println("broker publish failed")
		return err
	}```

**Comment by printfcoder** [comment]
Hi，请参考 [nsq链接](https://github.com/micro-in-cn/tutorials/tree/master/examples/basic-practices/micro-broker/kafka)

如果不行，那应该是Kafka集群搭建有问题

**Comment by yeaze** [comment]
@printfcoder 按照你给的参考改了下，我这是以grpc作为通信的，现在订阅的方法应该被触发了，只是报错了：

```
panic: interface conversion: kh_micro_srv_khlog.Message is not proto.Message: missing method ProtoMessage

goroutine 83 [running]:
github.com/micro/go-micro/server/grpc.protoCodec.Unmarshal(...)
	/home/gcc/go_workspace/pkg/mod/github.com/micro/go-micro@v1.10.0/server/grpc/codec.go:75
github.com/micro/go-micro/server/grpc.(*grpcServer).createSubHandler.func1(0x178fd40, 0xc00026e280, 0x80, 0xa4)
	/home/gcc/go_workspace/pkg/mod/github.com/micro/go-micro@v1.10.0/server/grpc/subscriber.go:205 +0x565
github.com/micro/go-plugins/broker/kafka.(*consumerGroupHandler).ConsumeClaim(0xc0000ca1e0, 0x179c8c0, 0xc00018c200, 0x1796f40, 0xc0001be2d0, 0xd, 0x0)
	/home/gcc/go_workspace/pkg/mod/github.com/micro/go-plugins@v1.3.0/broker/kafka/options.go:50 +0x1a2
github.com/Shopify/sarama.(*consumerGroupSession).consume(0xc00018c200, 0xc0000bc0f0, 0xd, 0x0)
	/home/gcc/go_workspace/pkg/mod/github.com/!shopify/sarama@v1.23.1/consumer_group.go:615 +0x27f
github.com/Shopify/sarama.newConsumerGroupSession.func2(0xc00018c200, 0xc0000bc0f0, 0xd, 0xc000000000)
	/home/gcc/go_workspace/pkg/mod/github.com/!shopify/sarama@v1.23.1/consumer_group.go:544 +0x95
created by github.com/Shopify/sarama.newConsumerGroupSession
	/home/gcc/go_workspace/pkg/mod/github.com/!shopify/sarama@v1.23.1/consumer_group.go:536 +0x526
exit status 2

```

**Comment by yeaze** [comment]
已经参照给的demo解决了，感谢
